### ISSUE TITLE
Unable to duplicate file/directory

### ISSUE THREAD

**Issue by carldunham** [sleistner/vscode-fileutils#209]
**Describe the bug**
Fails silently (with error in "Log (Extension Host)" output window).

**To Reproduce**
1. Open a project
2. Right click on a directory
3. Sleect "Duplicate"
3. See error

**Expected behavior**
Duplication flow happens

**Screenshots**
```
[2020-06-14 17:41:30.263] [exthost] [error] Activating extension sleistner.vscode-fileutils failed due to an error:
[2020-06-14 17:41:30.265] [exthost] [error] Error: Cannot find module '/Users/cdunham/.vscode/extensions/sleistner.vscode-fileutils-3.0.1/out/src/extension'
Require stack:
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-amd.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-fork.js
	at Function.Module._resolveFilename (internal/modules/cjs/loader.js:717:15)
	at Module._load (internal/modules/cjs/loader.js:622:27)
	at Module._load (electron/js2c/asar.js:717:26)
	at Function.Module._load (electron/js2c/asar.js:717:26)
	at Function.t._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:974:268)
	at Function.i._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:943:114)
	at Function.n._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:939:443)
	at Module.require (internal/modules/cjs/loader.js:775:19)
	at require (internal/modules/cjs/helpers.js:68:18)
	at Function.s [as __$__nodeRequire] (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:33:115)
	at h._loadCommonJSModule (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:944:266)
	at h._doActivateExtension (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:838:856)
	at h._activateExtension (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:837:937)
	at Object.actualActivateExtension (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:835:883)
	at e._activateExtension (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:609:859)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:609:537
	at Array.map (<anonymous>)
	at e._activateExtensions (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:609:525)
	at e.activateByEvent (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:607:14)
	at h._activateByEvent (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:836:618)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:846:159
	at processTicksAndRejections (internal/process/task_queues.js:85:5)
```

**Desktop (please complete the following information):**
- VSCode Version: Version: 1.46.0
Commit: a5d1cc28bb5da32ec67e86cc50f84c67cc690321
Date: 2020-06-10T08:59:06.977Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.5.0
- OS Version: macOS Catalina (10.15.5)
- Extension version 3.0.1

**Additional context**
Have tried uninstalling and reinstalling the extension

**Comment by sleistner** [comment]
Hi Carl, thank you for reporting this issue. Unfortunately I am unable to reproduce the described behaviour. Could you please verify if the failure happens on other directories, and-or other projects as well?

**Comment by carldunham** [comment]
I did try a few other projects, same results. There seem to be files missing?
```
% ls -lR ~/.vscode/extensions/sleistner.vscode-fileutils-3.0.1/
total 32
-rw-r--r--  1 cdunham  staff  7947 Jan 15 15:53 CHANGELOG.md
drwxr-xr-x  5 cdunham  staff   160 Apr 18 06:49 images
drwxr-xr-x  3 cdunham  staff    96 Jan 15 15:53 out
-rw-r--r--  1 cdunham  staff  5453 Jan 15 15:53 package.json

/Users/cdunham/.vscode/extensions/sleistner.vscode-fileutils-3.0.1//images:
total 1704
-rw-r--r--  1 cdunham  staff  830883 Jan 15 15:53 demo.gif
-rw-r--r--  1 cdunham  staff   17431 Jan 15 15:53 howto.png
-rw-r--r--  1 cdunham  staff   19662 Jan 15 15:53 icon.png

/Users/cdunham/.vscode/extensions/sleistner.vscode-fileutils-3.0.1//out:
total 0
drwxr-xr-x  5 cdunham  staff  160 Apr 16 21:48 src

/Users/cdunham/.vscode/extensions/sleistner.vscode-fileutils-3.0.1//out/src:
total 0
drwxr-xr-x  2 cdunham  staff  64 Apr 16 20:23 command
drwxr-xr-x  2 cdunham  staff  64 Apr 16 22:05 controller
drwxr-xr-x  2 cdunham  staff  64 Apr 16 21:17 lib

/Users/cdunham/.vscode/extensions/sleistner.vscode-fileutils-3.0.1//out/src/command:

/Users/cdunham/.vscode/extensions/sleistner.vscode-fileutils-3.0.1//out/src/controller:

/Users/cdunham/.vscode/extensions/sleistner.vscode-fileutils-3.0.1//out/src/lib:
%
```

**Comment by sleistner** [comment]
That is indeed weird. I reinstalled the extension (and removed the directory) but getting the following:
```
/Users/sleistner/.vscode/extensions/sleistner.vscode-fileutils-3.0.1/out/src
├── FileItem.js
├── command
│   ├── BaseCommand.js
│   ├── Command.js
│   ├── CopyFileNameCommand.js
│   ├── DuplicateFileCommand.js
│   ├── MoveFileCommand.js
│   ├── NewFileAtRootCommand.js
│   ├── NewFileCommand.js
│   ├── NewFolderAtRootCommand.js
│   ├── NewFolderCommand.js
│   ├── RemoveFileCommand.js
│   ├── RenameFileCommand.js
│   └── index.js
├── controller
│   ├── BaseFileController.js
│   ├── CopyFileNameController.js
│   ├── DuplicateFileController.js
│   ├── FileController.js
│   ├── MoveFileController.js
│   ├── NewFileController.js
│   ├── RemoveFileController.js
│   ├── TypeAheadController.js
│   └── index.js
├── extension.js
└── lib
    ├── Cache.js
    ├── TreeWalker.js
    └── config.js
```

**Comment by carldunham** [comment]
OK, so I tried uninstalling the extension and reinstalling, same result. But then I tried uninstalling it, and removed `/.vscode/extensions/sleistner.vscode-fileutils-3.0.1 and reinstalled, now it works. Not sure what happened there, but all good now. Thanks!
