### ISSUE TITLE
IGNORING workspace edit: NoPermissions on file renaming

### ISSUE THREAD

**Issue by ryzhovalex** [sleistner/vscode-fileutils#506]
**Describe the bug**
A file does not change name after using renaming command.

**To Reproduce**
1. Open VSCode with any project in your home directory
2. Create file "test.py" with any content
3. Call File Utils: Rename and rename "test.py" -> "anything.py"
4. See that the file name isn't changed, the prompt is closed

**Expected behavior**
Rename a file using File Utils: Rename.

**Desktop (please complete the following information):**
- VSCode Version: 1.74.3
- OS Version: Linux x64 6.1.6-zen1-1-zen
- FileUtils Extension Version: 3.8.0

**Additional context**
VSCode logs related to File Utils:
```
2023-01-25 12:41:51.097 [error] NoPermissions (FileSystemError): Error: EACCES: permission denied, copyfile '/home/alex/dev/file-utils-test/test.py' -> '/anything.py'
    at l (/opt/visual-studio-code/resources/app/out/vs/code/electron-main/main.js:34:4023)
    at i.Y (/opt/visual-studio-code/resources/app/out/vs/code/electron-main/main.js:39:36565)
    at i.rename (/opt/visual-studio-code/resources/app/out/vs/code/electron-main/main.js:39:34724)
2023-01-25 12:41:51.098 [warning] IGNORING workspace edit: NoPermissions (FileSystemError): Error: EACCES: permission denied, copyfile '/home/alex/dev/file-utils-test/test.py' -> '/anything.py'
```

Seems like on renaming copying is made, and according to logs File Utils tries to copy renamed file into root directory "/anything.py".

**Comment by adamjosefus** [comment]
Same issue. macOS 13.2

**Comment by sleistner** [comment]
Thank you, that one slipped through the tests. It is going to be addressed with a new release later today. https://github.com/sleistner/vscode-fileutils/pull/504
