### ISSUE TITLE
Update to 3.10.1 fails

### ISSUE THREAD

**Issue by simonknittel** [sleistner/vscode-fileutils#547]
**Describe the bug**
Updating to version `3.10.1` fails with the following error:

```
2023-03-27 09:19:40.729 [error] CorruptZip: end of central directory record signature not found
    at yt.download (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:91:223)
    at async X.x (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:91:20760)
    at async X.h (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:91:18897)
2023-03-27 09:19:40.761 [error] end of central directory record signature not found: CorruptZip: end of central directory record signature not found
    at yt.download (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:91:223)
    at async X.x (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:91:20760)
    at async X.h (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:91:18897)
```

**To Reproduce**
1. Go to 'Extensions' > 'File Utils'
2. Click on 'Update'
3. See error

**Expected behavior**
Update completes successfully and having version 3.10.1 installed.

**Desktop (please complete the following information):**
- VSCode Version: 1.76.2
- OS Version: 13.2.1
- FileUtils Extension Version: 3.10.0

**Additional context**
I've never seen an issue like this with any other extension. Updates of other extensions still work fine.

**Comment by sleistner** [comment]
Maybe related https://github.com/microsoft/vscode/issues/71610

**Comment by simonknittel** [comment]
Hi @sleistner, thanks for the quick response. However, that doesn't work either. It results in the same error.

**Comment by simonknittel** [comment]
Seems like a few of these issues popped up last few days: https://github.com/microsoft/vscode/issues?q=end+of+central+directory+record+signature+not+found+sort%3Aupdated-desc

**Comment by simonknittel** [comment]
Today's VSCode update to 1.77.0 temporarily disables the signature verification until the team fixed the actual issue.

This let's me install this extension again.

I'm closing this since this extension isn't the cause of thhe issue.
